apiVersion: v1
kind: ConfigMap
metadata:
  name: flask
  namespace: default
data:
  FLASK_PORT: "6000"
  FLASK_DEBUG: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-nginx
  namespace: default
data:
  default.conf: |
    server {
        listen 80;

        server_name _;

        # TODO: setup cors
        # add_header Access-Control-Allow-Origin localhost:1313;

        location ~ \.(css|js|jpg|png|jpeg|webp|gif|svg) {
            root /app/public;
        }

        location / {
            proxy_set_header Host $host ;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto: http;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_pass http://127.0.0.1:5000;
            proxy_read_timeout 10;
        }
    }
